options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "us-central1"
  _AR_REPO: "weather-repo"
  _IMAGE: "weather-api"
  _CLUSTER: "moj-gke-klaster"

steps:
  # 1. Build JAR
  - name: "maven:3.8.4-openjdk-17"
    entrypoint: "mvn"
    args: ["package", "-DskipTests"]

  # 2. Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:${SHORT_SHA}",
        ".",
      ]

  # 3. Push image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:${SHORT_SHA}",
      ]

  # 4. Authenticate to GKE cluster
  # same as: gcloud container clusters get-credentials moj-gke-klaster --region=us-central1
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "container",
        "clusters",
        "get-credentials",
        "${_CLUSTER}",
        "--region=${_REGION}",
        "--project=$PROJECT_ID",
      ]

  # 6. Apply configs
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "k8s/"]
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_REGION}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}"

  # 7. Update deployment image in GKE
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment/${_IMAGE}",
        "${_IMAGE}=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:${SHORT_SHA}",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_REGION}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE}:${SHORT_SHA}"
